---
title: Test_all_prm_10"
output:
  pdf_document: default
  html_notebook: default
---

# 0. Load packages
```{r}
library(VGAM)
library(tidyverse)
# library(slider)
library(foreach)
library(doParallel)
rm(list = ls())

start.time = Sys.time() # record running time
```

# 1. Set parameters
```{r}
# set scale and size
prm = tibble(scale = seq(0.5, 2, length.out = 7),
             size = exp(seq(log(0.1), log(4), length.out=7)))
```

# 2. Read data
```{r}
Data = read_rds("./ReadData/La04_0-10Ma.Rdata") %>% 
  rename(time_yr = V1, ETP = V2) %>% 
  head(2e6) # 2 Myr duration
```

# 3. Computation
```{r}
for (k in 1:10) { # times of test
  
  for (i in 1:7) {
    
    for(j in 1:7) { # [size, scale] = [i, j]
      
      output = Data %>% 
        mutate(sed.m = 1e-4, # mean sedimentation rate of 10 cm/kyr
               sed.rate.ds = runif(length(time_yr), 0, 1) + sed.m,
               left = sed.rate.ds < 0.5, right = !left,
               sed.rate = row_number(NA))
      
      # Set distribution of sedimentation rates
      sed.rate.left = -rtruncpareto(sum(output$left), 1, prm$size[i]*1000,  prm$scale[j])+1
      sed.rate.right = rtruncpareto(sum(output$right), 1, prm$size[i]*1000, prm$scale[j])-1
      output$sed.rate[output$left] = sed.rate.left
      output$sed.rate[output$right] = sed.rate.right
    
      output = output %>%
        mutate(sed.rate = sed.rate/1000 + sed.m,
               beds = round(cumsum(sed.rate), digits = 5),  #to create bed elevations from instantaneous sed rates
               bed.start = c(0, beds[-length(beds)]),
               bed.end = beds,
               bed.min = row_number(NA))
      
      # Parallel computing
      cores = detectCores(logical = FALSE)
      cl = makeCluster(cores)
      registerDoParallel(cl)
  
      # Calculate bed elevation
      output$bed.min = foreach(n = 1:length(output$bed.end)) %dopar% {
        if(n == length(output$bed.end))
          return(output$bed.end[n])
        return(min(output$bed.end[n:length(output$bed.end)]))
        }
      
      stopImplicitCluster()
      stopCluster(cl)
      
      # Save outputs
      output = output %>% 
        mutate(is.erosion = if_else(bed.min <= bed.start, T, F),
               is.preserved = !is.erosion) %>% 
        select(-c(left, right, bed.min, beds, sed.rate.ds, is.erosion, sed.m)) # delete these columns
      
      # Define directory names
      name.dir1 = paste0("./Outputs/Test_all_prm/Test_all_prm_Rdata/Test_all_prm_Rdata_", i, ".", j)
      name.dir2 = paste0("./Outputs/Test_all_prm/Test_all_prm_depth/Test_all_prm_depth_", i, ".", j)
      name.dir3 = paste0("./Outputs/Test_all_prm/Test_all_prm_time/Test_all_prm_time_",  i, ".", j)
      dir.create(name.dir1, recursive = TRUE)
      dir.create(name.dir2, recursive = TRUE)
      dir.create(name.dir3, recursive = TRUE)
      
      name1 = paste0(name.dir1, "/Test_all_prm_Rdata_", i, ".", j, "_", k, ".rds")
      name2 = paste0(name.dir2, "/Test_all_prm_depth_", i, ".", j, "_", k, ".csv")
      name3 = paste0(name.dir3, "/Test_all_prm_time_", i, ".", j, "_", k, ".csv")
      
      write_rds(output, name1)
      
      write.table(cbind(output$bed.end[output$is.preserved],
                        output$ETP[output$is.preserved]), 
                  name2, sep = ",",
                  col.names = F, 
                  row.names = F) # write depth domain
      
      write.table(cbind(output$time_yr[output$is.preserved],
                        output$ETP[output$is.preserved]), 
                  name3, sep = ",", 
                  col.names = F, 
                  row.names = F) # write time domain
    }
  }
}

end.time = Sys.time()
time.taken = round(end.time - start.time, 2)
time.taken
```
